(define (mainI age_bst give_age)
(cond ((is_empty? age_bst) '(() ()))
((= (get-val age_bst) give_age) (list (get-eldest (get-lst (search age_bst give_age))) (get-youngest (get-rst (search age_bst give_age)))))
((> (get-val age_bst) give_age)
(cond ((null? (cadr (main (get-lst age_bst) give_age))) (list (car (main (get-lst age_bst) give_age)) (get-val age_bst)))
(else (main (get-lst age_bst) give_age)))
)
(else (cond ((null? (car (main (get-rst age_bst) give_age))) (list (get-val age_bst) (cadr (main (get-rst age_bst) give_age))))
(else (main (get-rst age_bst) give_age)))
)
)
)
